export const DETAIL_MOVIE_REQUEST = "@listmovie/DETAIL_MOVIE_REQUEST";
export const DETAIL_MOVIE_SUCCESS = "@listmovie/DETAIL_MOVIE_SUCCESS";
export const DETAIL_MOVIE_FAILED = "@listmovie/DETAIL_MOVIE_FAILED";